---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  FB_TOKEN: create_facebook_token
  SESSION_SECRET: session_token
test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  FB_TOKEN: create_facebook_token
  SESSION_SECRET: session_token
production:
  FB_TOKEN: create_facebook_token
