---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  FB_TOKEN: create_facebook_token
  FB_USERNAME: user_account
  FB_PASSWORD: user_password
  MAILGUN_API_KEY: api_key
  MAILGUN_DOMAIN_NAME: domain_name

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  FB_TOKEN: create_facebook_token
  FB_USERNAME: user_account
  FB_PASSWORD: user_password
  MAILGUN_API_KEY: api_key
  MAILGUN_DOMAIN_NAME: domain_name

